### ISSUE TITLE
Fix Home Page Header and Image Alignment

### ISSUE THREAD

**Issue by TryOmar** [Omar7001-B/data-miner#18]
### Description
The header and image on the Home page are not properly centered. This affects the visual appearance and professional look of the application's landing page.

### Current Behavior
Looking at `Home.py`, the current implementation uses columns and custom HTML:
```python
col1, col2, col3 = st.columns([2, 3, 2])
with col2:
    st.markdown('''
    <div style="display: flex; flex-direction: column; align-items: center; justify-content: center; text-align: center;">
    ''', unsafe_allow_html=True)
    st.image("assets/logo.png", width=200)
    st.markdown('''
        <h1 style="margin: 1rem 0;">Welcome to DataMiner!</h1>
        <h3 style="margin: 0.5rem 0;">Your Data Analysis Companion</h3>
        <p>Explore, visualize, and transform your data effortlessly with DataMiner.</p>
    </div>
    ''', unsafe_allow_html=True)
```

However, this implementation is not achieving proper centering of all elements.

### Expected Behavior
- Logo image should be perfectly centered on the page
- Header text should be centered and aligned with the logo
- All elements in the header section should maintain consistent spacing
- The entire header section should be visually balanced

### Technical Solution
1. Update the CSS in `assets/style.css` to handle centering:
```css
.header-container {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    text-align: center;
    width: 100%;
    margin: 2rem 0;
}

.header-container img {
    margin-bottom: 1.5rem;
}

.header-container h1 {
    margin: 1rem 0;
}

.header-container h3 {
    margin: 0.5rem 0;
    color: var(--text-color);
}

.header-container p {
    margin-top: 0.5rem;
    color: var(--text-color);
}
```

2. Update the Home.py markup to use these classes:
```python
st.markdown('''
<div class="header-container">
    <img src="assets/logo.png" width="200">
    <h1>Welcome to DataMiner!</h1>
    <h3>Your Data Analysis Companion</h3>
    <p>Explore, visualize, and transform your data effortlessly with DataMiner.</p>
</div>
''', unsafe_allow_html=True)
```

### Files to Modify
- `Home.py`
- `assets/style.css`

### Additional Notes
- Consider using Streamlit's native components where possible
- Ensure responsive design for different screen sizes
- Test the centering on different browsers and devices

> ASSISTED BY AI — OMAR ABBAS
